
on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: macos-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Setup Theos
        uses: Randomblock1/theos-action@v1
      -
        name: Setting up GNU Make
        run: |
          brew install make
          echo PATH=\"$(brew --prefix make)/libexec/gnubin:\$PATH\" >> ~/.zprofile
          source ~/.zprofile
      -
        name: Build packages
        run: |
          mkdir output
          sed -i "" "s#Icon:#Icon: https://github.com/hekatos/repo/blob/c5824ef27c413de29ca8e5fbe2bb95ca9d08f5fb/icons/GenshinJailbreakBypass.png#" /Users/runner/work/tweaks/tweaks/GenshinJailbreakBypass/control
          find . -maxdepth 1 -not -path . -type d -not -name '.git' -not -name 'theos' -exec make -C '{}' package FINALPACKAGE=1 \; 
          find . -type f -iname *.deb -exec mv '{}' output \;
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: output/*
